### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by binarykitchen** [intesso/connect-livereload#79]
```
TypeError: Cannot read property 'split' of undefined
   at Object.livereload [as handle] (/home/michael-heuberger/code/videomail-client/node_modules/connect-livereload/index.js:91:49)
   at next (/home/michael-heuberger/code/videomail-client/node_modules/connect/lib/proto.js:174:15)
   at Function.app.handle (/home/michael-heuberger/code/videomail-client/node_modules/connect/lib/proto.js:182:3)
   at Http2SecureServer.app (/home/michael-heuberger/code/videomail-client/node_modules/connect/lib/connect.js:67:37)
   at emitTwo (events.js:131:20)
   at Http2SecureServer.emit (events.js:214:7)
   at Http2SecureServer.onServerStream (internal/http2/compat.js:710:10)
   at emitMany (events.js:147:13)
   at Http2SecureServer.emit (events.js:224:7)
   at ServerHttp2Session.sessionOnStream (internal/http2/core.js:2304:17)
```

Using "gulp-connect": "5.2.0" here

**Comment by nickpape-msft** [comment]
I am seeing this issue as well with Node 8, I found a potential workaround that seems to work. I'll link a PR shortly.

**Comment by matt3224** [comment]
I'm seeing this on node 9 too, whats the workaround?

**Comment by terence1990** [comment]
This is likely because of lack of http2 support, where the request sends authority header instead of host, the solution is to use up to node 8.1.2 and to uninstall the http2 module which causes connect to favour it

**Comment by rahul-desai3** [comment]
Still seeing this in Node 9.3, works on Node 8.3 though.

**Comment by binarykitchen** [comment]
Any news on this old one? Still happening and it's a pain :(

**Comment by nasir-mps** [comment]
same issue with node version 10.12.0

**Comment by ksac1** [comment]
What is the solution for the issue: TypeError: Cannot read property 'split' of undefined ?

**Comment by sergeymorkovkin** [comment]
Confirm.

**Comment by ksac1** [comment]
@sergeymorkovkin : what is confirmed?

**Comment by sergeymorkovkin** [comment]
Tried to enable https and got this error. Using node@11.10.1, http2@3.3.7 (even though it's marked deprecated).
